config/routes.rb
Rails.application.routes.draw do
  resources :friends
  devise_for :users
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end
  # root "home#index"
  root "friends#index"
  # get "home/about" => "home#about", as: :about
  get "home/about"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :correct_user, only: [ :edit, :update, :destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
    # The above line ensures that the friend is associated with the current user
    # and prevents unauthorized access to other users' friends.
    # This is important for security and data integrity in a multi-user application.
    # It also allows the application to easily access the current user's friends
    # without needing to pass the user ID explicitly.
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)
    # The above line ensures that the friend is associated with the current user
    # and prevents unauthorized access to other users' friends.
    # This is important for security and data integrity in a multi-user application.
    # It also allows the application to easily access the current user's friends
    # without needing to pass the user ID explicitly.

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friends_path, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_content }
        format.json { render json: @friend.errors, status: :unprocessable_content }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_path, status: :see_other, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized to edit this friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.expect(friend: [ :first_name, :last_name, :email, :phone, :twiter, :name, :comment, :age_num, :birth_date, :salary_amt, :isbest, :user_id ])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_me = "My name is FJR"
    @answer = 2 + 2
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<div class="card" style="width: 30rem";>
  <%= form_with(model: friend) do |form| %>
    <% if friend.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>
        <ul>
          <% friend.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="card-header">
        <% if @friend.new_record? %>
          <h2 class="card-title">New Friend</h2>
        <% else %>
          <h2 class="card-title">Edit Friend</h2>
        <% end %>
    </div>

    <div class="card-body">
      <div class="form-group">
        <%= form.label :first_name, style: "display: block" %>
        <%= form.text_field :first_name, placeholder: "First Name", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :last_name, style: "display: block" %>
        <%= form.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :email, style: "display: block" %>
        <%= form.text_field :email, placeholder: "Email", class: "form-control w-50" %>
      </div>

      <div class="form-group">
        <%= form.label :phone, style: "display: block" %>
        <%= form.text_field :phone, placeholder: "Phone", class: "form-control w-50" %>
      </div>

      <div class="form-group">
        <%= form.label :twiter, style: "display: block" %>
        <%= form.text_field :twiter, placeholder: "Twitter", class: "form-control w-50"  %>
      </div>

      <div class="form-group">
        <%= form.label :name, style: "display: block" %>
        <%= form.text_field :name, placeholder: "Name", class: "form-control"  %>
      </div>

      <div class="form-group">
        <%= form.label :comment, style: "display: block" %>
        <%= form.textarea :comment, placeholder: "Comment", class: "form-control"  %>
      </div>

      <div class="form-group">
        <%= form.label :age_num, style: "display: block" %>
        <%= form.number_field :age_num, placeholder: "Age", class: "form-control  w-25"  %>
      </div>

      <div class="form-group">
        <%= form.label :birth_date, style: "display: block" %>
        <%= form.date_field :birth_date, placeholder: "Birth Date", class: "form-control w-50"  %>
      </div>

      <div class="form-group">
        <%= form.label :salary_amt, style: "display: block" %>
        <%= form.text_field :salary_amt, placeholder: "Salary", class: "form-control w-25"   %>
      </div>

      <div class="form-group">
        <%= form.label :isbest, "Best Friend?", style: "display: block" %>
        <%= form.checkbox :isbest, class: "form-check-input" %>
      </div>

      <div ="form-group">
        <%= form.number_field :user_id,id: :friend_user_id, value: current_user.id, type: "hidden" %>
      </div>
    </div>

    <div class="card-footer d-flex">
      <% if @friend.new_record? %>
        <%= form.submit "Save",  class: "btn btn-primary ms-auto me-3" %>

      <% else %>
        <%= form.submit "Update",  class: "btn btn-primary ms-auto me-3" %>

      <% end %>

      <%= link_to "Cancel", friends_path, class: "btn btn-secondary" %>
    </div>

  <% end %>
</div>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twiter:</strong>
    <%= friend.twiter %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= friend.name %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= friend.comment %>
  </p>

  <p>
    <strong>Age num:</strong>
    <%= friend.age_num %>
  </p>

  <p>
    <strong>Birth date:</strong>
    <%= friend.birth_date %>
  </p>

  <p>
    <strong>Salary amt:</strong>
    <%= friend.salary_amt %>
  </p>

  <p>
    <strong>Isbest:</strong>
    <%= friend.isbest %>
  </p>

</div>

app/views/friends/edit.html.erb
<% content_for :title, "Edit friend" %>

<%= render "form", friend: @friend %>

<br>
    <%= button_to "Delete", @friend, 
            data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, 
            method: :delete, class: "btn btn-danger me-3" %>

app/views/friends/index.html.erb
<% if user_signed_in? %>
  <% content_for :title, "Friends" %>

  <h1>Friends</h1>

  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th class = "w-auto">Name</th>
        <th class = "w-auto">Email</th>
        <th class = "w-auto">Phone</th>
        <th class = "w-auto">Twitter</th>
      </tr>
    </thead>
    <tbody>
      <% @friends.each do |friend| %>
        <% if friend.user == current_user %>
          <tr>
            <td class = "w-auto">
              <%= link_to "#{friend.first_name} #{friend.last_name}", edit_friend_path(friend) %>
            </td>
            <td class = "w-auto"><%= friend.email %></td>
            <td class = "w-auto"><%= friend.phone %></td>
            <td class = "w-auto"><%= friend.twiter %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <%= link_to "New friend", new_friend_path, class: "btn btn-primary" %>

<% else %>
  <h1>Welcome to the Friends App</h1>
  <br>
  <h4>This is a demo of my Rails applications.</h4>
  <br>
  <p>Please sign in to manage your friends.</p>
  <%= link_to "Sign In", new_user_session_path, class: "btn btn-primary" %>
  <br><br>
  <%= link_to "Sign Up", new_user_registration_path %>

<% end %>

app/views/friends/new.html.erb
<% content_for :title, "New friend" %>

<%= render "form", friend: @friend %>

app/views/friends/show.html.erb
<div class="card" style="width: 30rem";>

  <div class="card-header">
    <h3>Friend</h3>
  </div>

  <div class="card-body">
    <%= render @friend %>
  </div>

  <div class="card-footer d-flex">
    <%= link_to "Edit", edit_friend_path(@friend), class: "btn btn-primary ms-auto me-3" %>
    <%= button_to "Delete", @friend, 
            data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, 
            method: :delete, class: "btn btn-danger me-3" %>
    <%= link_to "Cancel", friends_path, class: "btn btn-secondary" %>
  </div>

</div>

app/views/home/about.html.erb
<h1>About Us</h1>
<p>I'm an IT Consultant and developer.</p>
<p>You may contact me at <a href=   "mailto: javier@fjrg.net">javier@fjrg.net</a>. Feel free to reach out for any inquiries or collaborations.</p>
<p>You may visit my website at <a href="https://www.fjrg.net" target="_blank">fjrg.net</a> for more information.</p>
<p>Thank you for visiting our demo site!</p>
<br>
<%= image_tag "it-ai.jpg"%>

app/views/home/index.html.erb
<h1>Hello World</h1>
<p>This is my first Rails application.</p>
<p>I hope you enjoy it!</p>
<%= image_tag "it-ai.jpg"%>

app/views/layouts/_alerts.html.erb
<% if notice %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-xxl bg-body-tertiary">
  <div class="container-fluid" style="background-color: rgb(20, 103, 159);">

    <%= image_tag "app_navbar_icon.png", height: 75, width: 75, alt: "App Icon", class: "navbar-brand-icon" %>
    <%= link_to "Friends App", root_path, class: "navbar-brand", style: "color: white;margin-left: 15px;" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-xxl-0">
        <%-  if user_signed_in? %>
          <%# <li class="nav-item">
              Add Links to application pages here
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" , style: "color: white;">
          </li> 
          Links to application pages can be added here
          %>
          <li class="nav-item">
            <%= link_to "Friends", friends_path, class: "nav-link" , style: "color: white;"%>
          </li>
          <li class="nav-item">
            <%= link_to "About Us", home_about_path, class: "nav-link" , style: "color: white;"%>
          </li>

        <%- else %>
          <li class="nav-item">
            <%= link_to "About Us", home_about_path, class: "nav-link" , style: "color: white;"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" , style: "color: white;"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" , style: "color: white;"%>
          </li>
        <%- end %>
      </ul>

      <form class="d-flex mb-auto" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-success me-5" type="submit" style="color: white;">Search</button>
      </form>

      <ul class="navbar-nav mb-2 mb-xxl-0">
        <%- if user_signed_in? %>
          <li class="nav-item dropdown me-3">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false", style= "color: white;">
              <%= current_user.email %>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
            </ul>
          </li>
        <%- end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Friends" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render'layouts/navbar' %>

    <div class="container">
      <br>
      <% if notice %>
        <%= render 'layouts/alerts', notice: notice %>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>